# Generated by Django 6.0.1 on 2026-04-03 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='banner_image')),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='category_image')),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateField(blank=True, null=True)),
                ('update_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='contactmessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('is_replied', models.CharField(max_length=100)),
                ('created_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('discount_type', models.CharField(max_length=100)),
                ('discount_value', models.IntegerField()),
                ('minimum_amount', models.IntegerField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='damagereport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental', models.CharField(max_length=100)),
                ('toy', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('fine_amount', models.BooleanField()),
                ('resolved', models.DateField(blank=True, null=True)),
                ('reportedss_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='siteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('logo', models.FileField(upload_to='siteSettings_logo')),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('late_fee_per_day', models.IntegerField()),
                ('deposit_policy', models.IntegerField()),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='toyimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toy', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='toyimage_image')),
                ('uploaded_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('age_group', models.CharField(max_length=255)),
                ('rental_price_per_day', models.IntegerField()),
                ('security_deposit', models.IntegerField()),
                ('stock_quantity', models.IntegerField()),
                ('available_quantity', models.IntegerField()),
                ('condition', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='toy_image')),
                ('is_available', models.BooleanField()),
                ('created_at', models.DateField(blank=True, null=True)),
                ('update_at', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.subcategory')),
            ],
        ),
    ]
