# Generated by Django 6.0.1 on 2026-04-08 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagereport',
            name='toy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.toy'),
        ),
        migrations.AlterField(
            model_name='toyimage',
            name='toy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.toy'),
        ),
    ]
