# Generated by Django 6.0.1 on 2026-04-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_damagereport_toy_alter_toyimage_toy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagereport',
            name='fine_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='toy',
            field=models.CharField(max_length=100),
        ),
    ]
