# Generated by Django 6.0.1 on 2026-04-08 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_damagereport_fine_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damagereport',
            name='toy',
        ),
        migrations.AddField(
            model_name='damagereport',
            name='toys',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminapp.toy'),
            preserve_default=False,
        ),
    ]
