# Generated by Django 6.0.1 on 2026-04-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_alter_category_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='toy',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='toy',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='toyimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
