# Generated by Django 6.0.1 on 2026-04-16 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_alter_toy_created_at_alter_toy_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damagereport',
            name='rental',
        ),
    ]
