# Generated by Django 6.0.1 on 2026-04-16 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_toy_added_by_alter_damagereport_reportedss_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.category'),
        ),
        migrations.AlterField(
            model_name='toy',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.subcategory'),
        ),
    ]
