# Generated by Django 6.0.1 on 2026-04-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_alter_toy_category_alter_toy_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='toyimage',
        ),
    ]
