# Generated by Django 6.0.1 on 2026-04-21 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_delete_toyimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toy',
            old_name='rental_price_per_day',
            new_name='rental_price_per_week',
        ),
    ]
