# Generated by Django 6.0.1 on 2026-04-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_rename_rental_price_per_day_toy_rental_price_per_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toy',
            name='whats_included',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(),
        ),
    ]
