# Generated by Django 6.0.1 on 2026-04-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_toy_long_description_toy_whats_included_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='description',
            field=models.TextField(),
        ),
    ]
