# Generated by Django 6.0.1 on 2026-04-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_rentalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Credit/Debit Card'), ('COD', 'Cash on Delivery')], default='CARD', max_length=20),
        ),
    ]
