# Generated by Django 6.0.1 on 2026-04-29 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_rentalrequest_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='is_extension',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='original_rental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extensions', to='adminapp.rentalrequest'),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='rental_duration_weeks',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='rental_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('PAID', 'Paid'), ('SHIPPED', 'Shipped'), ('DELIVERING', 'Out for Delivery'), ('COMPLETED', 'Delivered')], default='PENDING', max_length=20),
        ),
    ]
