# Generated by Django 6.0.1 on 2026-05-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_rentalrequest_is_extension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='toy',
            name='is_on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='toy',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='toy',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
