# Generated by Django 6.0.1 on 2026-04-03 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('toy', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('rental_start_date', models.DateField(blank=True, null=True)),
                ('rental_end_date', models.DateField(blank=True, null=True)),
                ('added_at', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LateFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental', models.CharField(max_length=100)),
                ('extra_days', models.IntegerField()),
                ('fee_per_day', models.IntegerField()),
                ('total_late_fee', models.IntegerField()),
                ('calculated_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental', models.CharField(max_length=100)),
                ('transaction_id', models.IntegerField()),
                ('payment_method', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('payment_status', models.CharField(max_length=100)),
                ('paid_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental', models.CharField(max_length=100)),
                ('refund_amount', models.IntegerField()),
                ('refund_status', models.CharField(max_length=100)),
                ('refund_date', models.DateField(blank=True, null=True)),
                ('refund_transaction_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_id', models.IntegerField()),
                ('user', models.CharField(max_length=100)),
                ('toy', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('rental_start_date', models.DateField(blank=True, null=True)),
                ('rental_end_date', models.DateField(blank=True, null=True)),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('total_days', models.IntegerField()),
                ('rental_amount', models.IntegerField()),
                ('security_deposit', models.IntegerField()),
                ('late_fee', models.IntegerField()),
                ('discount_amount', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=100)),
                ('created_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('return_reason', models.CharField(max_length=100)),
                ('approval_status', models.BooleanField()),
                ('requested_at', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rentalitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toy', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('price_per_day', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.rental')),
            ],
        ),
    ]
