# Generated by Django 6.0.1 on 2026-04-14 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalitem',
            old_name='rental',
            new_name='rentalid',
        ),
    ]
