# Generated by Django 6.0.1 on 2026-04-14 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0002_rename_rental_rentalitem_rentalid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalitem',
            old_name='rentalid',
            new_name='rental_id',
        ),
    ]
