# Generated by Django 6.0.1 on 2026-04-15 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0003_rename_rentalid_rentalitem_rental_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latefee',
            name='rental',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='rental',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='rental',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='rental',
        ),
        migrations.AddField(
            model_name='latefee',
            name='rental_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rentalapp.rental'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='rental_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rentalapp.rental'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refund',
            name='rental_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rentalapp.rental'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='rental_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rentalapp.rental'),
            preserve_default=False,
        ),
    ]
