# Generated by Django 6.0.1 on 2026-04-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0004_remove_latefee_rental_remove_payment_rental_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='user',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='rentalitem',
            old_name='rental_id',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='rental_id',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='rental_id',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='rental_id',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='rental_id',
        ),
    ]
