# Generated by Django 6.0.1 on 2026-04-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0005_rename_user_rental_user_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalitem',
            old_name='user_name',
            new_name='rental_number',
        ),
        migrations.AddField(
            model_name='rental',
            name='rental_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
