# Generated by Django 6.0.1 on 2026-04-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0006_rename_user_name_rentalitem_rental_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rental_number',
            field=models.IntegerField(),
        ),
    ]
